# -*- coding: utf-8 -*-
"""
test_run_carbonate_buffers_plus_commercial.py

Runs carbonate validation cases:
- Case 1: 0.1 M NaHCO3 (fresh)              ~ pH 8.3 @ 25C (informal reference)
- Case 2: NIST carbonate standard            pH(S)=10.012 @ 25C (0.025 m + 0.025 m)
- Commercial-like carbonate buffer cases:
  - pH 10.01 @ 25C (typically same carbonate standard in CRMs)
  - pH 10.00 @ 20–25C (generic carbonate pH 10 products)
  - pH 10.65 (recipe target; not a common certified pH standard)

Notes:
- The "commercial-like" pH 10.00 and pH 10.65 cases are generated by selecting a total TIC and
  picking NaHCO3/Na2CO3 proportions using a HH ratio on pKa2. This gives you a plausible
  carbonate buffer composition to validate solver behavior.
"""

import os
import numpy as np

HERE = os.path.dirname(os.path.abspath(__file__))
os.chdir(HERE)

from speciation.engine import BisectionChemicalEquilibriumEngine


def carbonate_salt_mix_for_target_pH(
    pH_target: float,
    *,
    CT_TIC: float,
    pKa2_guess: float = 10.33,
) -> dict:
    """
    Build a simple carbonate/bicarbonate salt mix to *aim* for pH_target.

    We assume the carbonate buffer pair HCO3- / CO3-- around pKa2:
        pH = pKa2 + log10([CO3--]/[HCO3-])

    Choose mole fractions for TIC:
        CT_TIC = [HCO3-] + [CO3--]  (as if we prepared from salts)
        ratio r = [CO3--]/[HCO3-] = 10^(pH - pKa2)

        => [HCO3-] = CT_TIC/(1+r)
           [CO3--] = CT_TIC - [HCO3-]

    Sodium needed from salts:
        NaHCO3 contributes 1 Na per HCO3-
        Na2CO3 contributes 2 Na per CO3--
        => CT_Na = 1*[HCO3-] + 2*[CO3--]

    Returns a dict with CT_TIC, CT_Na and the "as-prepared" split.
    """
    r = 10 ** (float(pH_target) - float(pKa2_guess))
    hco3 = float(CT_TIC) / (1.0 + r)
    co3 = float(CT_TIC) - hco3
    na = hco3 + 2.0 * co3
    return {
        "CT_TIC": float(CT_TIC),
        "CT_Na": float(na),
        "prep_HCO3": hco3,
        "prep_CO3": co3,
        "ratio_CO3_to_HCO3": float(r),
        "pKa2_guess": float(pKa2_guess),
        "pH_target": float(pH_target),
    }


def run_case(
    name: str,
    *,
    CT_TIC: float,
    CT_Na: float,
    expected_pH: float,
    tol: float = 0.15,
    level: int = 2,
    use_activity: bool = True,
    activity_model: str = "davies",
    T_C: float = 25.0,
    debug_species: bool = True,
):
    engine = BisectionChemicalEquilibriumEngine(
        level=level,
        use_activity=use_activity,
        activity_model=activity_model,
        T_C=T_C,
    )

    out = engine.solve(
        acid_totals={},
        acid_pKas={},
        CT_TIC=CT_TIC,
        CT_P=0.0,
        CT_NH_T=0.0,
        CT_Na=CT_Na,
        CT_Cl=0.0,
        CT_K=0.0,
        CT_NO3=0.0,
        CT_SO4=0.0,
        CT_Mg=0.0,
        CT_Ca=0.0,
        CT_Zn=0.0,
        CT_Mn=0.0,
        CT_Co=0.0,
        CT_Mo7O24=0.0,
        pH_min=0.0,
        pH_max=14.0,
        n_scan=800,
        tol=1e-12,
    )

    pH = float(out.get("pH", np.nan))
    I = float(out.get("IonicStrength", np.nan))
    ok = abs(pH - expected_pH) <= tol

    print(f"\n{name}")
    print(f"  Inputs: CT_TIC={CT_TIC:.6g} M, CT_Na={CT_Na:.6g} M")
    print(f"  Pred:   pH={pH:.4f}, I={I:.5g} M")
    print(f"  Target: pH≈{expected_pH:.3f} (±{tol:.3f})  ->  {'PASS' if ok else 'FAIL'}")

    if debug_species:
        for k in ["CO2aq", "HCO3-", "CO3--", "H+", "OH-", "Na+", "aH"]:
            if k in out:
                print(f"    {k:6s}: {out[k]}")

    return ok, out


if __name__ == "__main__":
    # Global settings for these tests
    LEVEL = 2
    USE_ACTIVITY = True
    ACTIVITY_MODEL = "davies"
    T_C = 25.0

    # -------------------------
    # Existing cases
    # -------------------------

    # Case 1: 0.1 M NaHCO3 (freshly prepared) ~ pH 8.3 (informal, depends on CO2 uptake, etc.)
    run_case(
        "Case 1: 0.1 M NaHCO3 (fresh)",
        CT_TIC=0.100,
        CT_Na=0.100,
        expected_pH=8.30,
        tol=0.20,
        level=LEVEL,
        use_activity=USE_ACTIVITY,
        activity_model=ACTIVITY_MODEL,
        T_C=T_C,
    )

    # Case 2: NIST carbonate standard: 0.025 m NaHCO3 + 0.025 m Na2CO3
    # Using molarity approx here (works well at these strengths).
    # TIC total = 0.050 M, Na total = 0.075 M
    run_case(
        "Case 2: NIST buffer 0.025 M NaHCO3 + 0.025 M Na2CO3",
        CT_TIC=0.050,
        CT_Na=0.075,
        expected_pH=10.012,
        tol=0.15,
        level=LEVEL,
        use_activity=USE_ACTIVITY,
        activity_model=ACTIVITY_MODEL,
        T_C=T_C,
    )

    # -------------------------
    # Commercial-like cases
    # -------------------------

    # Commercial certified pH 10.01 buffers are commonly based on the carbonate standard.
    # We'll test the same composition but set expected pH to 10.01.
    run_case(
        "Case 3 (Commercial): Carbonate calibration buffer pH 10.01 (standard composition)",
        CT_TIC=0.050,
        CT_Na=0.075,
        expected_pH=10.010,
        tol=0.15,
        level=LEVEL,
        use_activity=USE_ACTIVITY,
        activity_model=ACTIVITY_MODEL,
        T_C=T_C,
    )

    # Commercial pH 10.00 "carbonate buffer" products often specify pH ~ 9.98–10.02 at ~20°C.
    # Here we *construct* a plausible carbonate/bicarbonate mix targeting 10.00 at 25°C.
    mix_10_00 = carbonate_salt_mix_for_target_pH(
        10.00,
        CT_TIC=0.050,      # choose a convenient TIC; you can change this
        pKa2_guess=10.33,  # approx pKa2 at 25°C in dilute solution
    )
    run_case(
        "Case 4 (Commercial-like): Carbonate/Bicarbonate buffer targeting pH 10.00 (constructed mix)",
        CT_TIC=mix_10_00["CT_TIC"],
        CT_Na=mix_10_00["CT_Na"],
        expected_pH=10.000,
        tol=0.20,  # looser because this is a constructed recipe, not a certified standard
        level=LEVEL,
        use_activity=USE_ACTIVITY,
        activity_model=ACTIVITY_MODEL,
        T_C=T_C,
    )
    print("  (Constructed mix details for pH 10.00)")
    print(f"    prep_HCO3={mix_10_00['prep_HCO3']:.6g} M, prep_CO3={mix_10_00['prep_CO3']:.6g} M")
    print(f"    CO3/HCO3={mix_10_00['ratio_CO3_to_HCO3']:.6g}, pKa2_guess={mix_10_00['pKa2_guess']:.3f}")

    # A higher-pH carbonate/bicarbonate recipe target (not typically a certified calibration point).
    mix_10_65 = carbonate_salt_mix_for_target_pH(
        10.65,
        CT_TIC=0.050,
        pKa2_guess=10.33,
    )
    run_case(
        "Case 5 (Recipe target): Carbonate/Bicarbonate buffer targeting pH 10.65 (constructed mix)",
        CT_TIC=mix_10_65["CT_TIC"],
        CT_Na=mix_10_65["CT_Na"],
        expected_pH=10.650,
        tol=0.25,
        level=LEVEL,
        use_activity=USE_ACTIVITY,
        activity_model=ACTIVITY_MODEL,
        T_C=T_C,
    )
    print("  (Constructed mix details for pH 10.65)")
    print(f"    prep_HCO3={mix_10_65['prep_HCO3']:.6g} M, prep_CO3={mix_10_65['prep_CO3']:.6g} M")
    print(f"    CO3/HCO3={mix_10_65['ratio_CO3_to_HCO3']:.6g}, pKa2_guess={mix_10_65['pKa2_guess']:.3f}")
